webdev/autenticacao/urls.py
from django.urls import path
from webdev.autenticacao import views

app_name = 'autenticacao'
urlpatterns = [
    path('registrar', views.registrar, name='registrar'),
]

webdev/tarefas/urls.py
from django.urls import path
from webdev.tarefas import views

app_name = 'tarefas'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:tarefa_id>', views.detalhe, name='detalhe'),
    path('apagar/<int:tarefa_id>', views.apagar, name='apagar'),
]

webdev/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('webdev.tarefas.urls')),
    path('', include('webdev.autenticacao.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
    )

webdev/tarefas/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Tarefa(models.Model):
    nome = models.CharField(max_length=128)
    feita = models.BooleanField(default=False)
    criada_em = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Tarefa {self.nome}'

webdev/tarefas/forms.py
from django.forms import ModelForm

from webdev.tarefas.models import Tarefa


class TarefaNovaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['nome']


class TarefaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['nome', 'feita']

webdev/autenticacao/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def registrar(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('tarefas:home'))

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password2')
                user = authenticate(username=username, password=password)
                login(request, user)
                return HttpResponseRedirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'registration/registrar.html', {'form': form})

webdev/tarefas/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from webdev.tarefas.forms import TarefaNovaForm, TarefaForm
from webdev.tarefas.models import Tarefa


@login_required
def home(request):
    if request.method == 'POST':
        form = TarefaNovaForm(request.POST)
        if form.is_valid():
            tarefa = form.save(commit=False)
            tarefa.usuario = request.user
            tarefa.save()
            return HttpResponseRedirect(reverse('tarefas:home'))
        else:
            tarefas_pendetes = Tarefa.objects.filter(feita=False, usuario_id=request.user).all()
            tarefas_feitas = Tarefa.objects.filter(feita=True, usuario_id=request.user).all()
            return render(
                request, 'tarefas/home.html',
                {
                    'form': form,
                    'tarefas_pendentes': tarefas_pendetes,
                    'tarefas_feitas': tarefas_feitas
                },
                status=400)
    tarefas_pendetes = Tarefa.objects.filter(feita=False, usuario_id=request.user).all()
    tarefas_feitas = Tarefa.objects.filter(feita=True, usuario_id=request.user).all()

    return render(
        request, 'tarefas/home.html',
        {
            'tarefas_pendentes': tarefas_pendetes,
            'tarefas_feitas': tarefas_feitas
        }
    )


def detalhe(request, tarefa_id):
    if request.method == 'POST':
        tarefa = Tarefa.objects.get(id=tarefa_id)
        form = TarefaForm(request.POST, instance=tarefa)
        if form.is_valid():
            form.save()
    return HttpResponseRedirect(reverse('tarefas:home'))


def apagar(request, tarefa_id):
    if request.method == 'POST':
        Tarefa.objects.filter(id=tarefa_id).delete()
    return HttpResponseRedirect(reverse('tarefas:home'))

webdev/tarefas/templates/tarefas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}To Do List {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'tarefas:home' %}">To Do List</a>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLogado" role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Olá {{ user.username | title }}!
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownLogado">
                        <div class="dropdown-item">
                            <a class="btn btn-danger" href="{% url 'logout' %}">Sair</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        {% endif %}
    </div>
</nav>
{% block content %}{% endblock %}
</body>
</html>

webdev/tarefas/templates/tarefas/home.html
{% extends "tarefas/base.html" %}
{% block title %}To Do List - Home{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="mt-5">Lista de tarefas</h1>
            <form action="{% url 'tarefas:home' %}" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Descreva a sua tarefa"
                           aria-label="Descreva a sua tarefa" aria-describedby="button-addon2" name="nome">
                    <button type="submit" class="btn btn-primary" id="button-addon2">Salvar</button>
                </div>
                <div class="form-text">{{ form.nome.errors }}</div>
            </form>

            <h2 class="mt-5">Tarefas pendentes</h2>
            {% for tarefa in tarefas_pendentes %}
            <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Descreva a sua tarefa"
                           required="required"
                           aria-label="Descreva a sua tarefa" name="nome" value="{{ tarefa.nome }}">
                    <input type="hidden" value="checked" name="feita">
                    <button type="submit" class="btn btn-success">Marcar como feita</button>
                </div>
            </form>
            {% endfor %}

            <h2 class="mt-5">Tarefas feitas</h2>
            {% for tarefa in tarefas_feitas %}
            <div class="row">
                <div class="col-2">
                    <form action="{% url 'tarefas:apagar' tarefa_id=tarefa.id %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <button type="submit" class="btn btn-danger">Apagar</button>
                        </div>
                    </form>
                </div>
                <div class="col-10">
                    <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Descreva a sua tarefa"
                                   required="required"
                                   aria-label="Descreva a sua tarefa" name="nome" value="{{ tarefa.nome }}">
                            <button type="submit" class="btn btn-warning">Marcar como pendente</button>
                        </div>
                    </form>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}